### PR TITLE
chore: config initial project

### PR DESCRIPTION
**Pull request by DorvilleThiago**

### CODE REVIEW

**Review by filipexxborba — APPROVED** [review]
Approve the changes, this is the initial state of the application.

**Review by filipexxborba — COMMENTED** [review]
Approve

**Review by luisroxis — APPROVED** [review]
Aprovado localmente

**Review by luisroxis — APPROVED** [review]
approved

**Review by devalyssonchiarelly — APPROVED** [review]
Approve

**Pull request merged**
